---
title: "Abbreviated Curriculum Vitae" 
author: "Mike Sandiford"
date: '`r Sys.Date()`'
---


```{r setup, include=FALSE}
library(tufte)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
library(stringr)
 library(scholar)
gs.id<-"qdYHZTgAAAAJ"
 my.cites=get_citation_history(gs.id)
 my.profile <- get_profile(gs.id)
 my.pubs1 <-get_publications(gs.id)
 
 gs <- function(title.str, pubs=my.pubs1, prefix= ", # citations "){
   sum.cites <- sum( pubs$cites[str_detect(str_to_lower(pubs$title), str_to_lower(title.str))])
   if (sum.cites > 0) paste(prefix,  sum.cites)
 }
```

full c.v. -  http://jaeger.earthsci.unimelb.edu.au/msandifo/cv/cv.full.pdf 

# Contextual statement
## Contributions to his discipline 
 
Professor Sandiford is an Australian geoscientists, recongnised for his scientific contributions across the geological and geophysical sciences.

His  research has focused on the linkages between the thermal and mechanical structure of the continents. His most notable contributions include:

* demonstrating how the feedbacks between primary tectonic processes (such as deformation, magmatism, erosion and sedimentation) serve to order the chemical structure of the continental crust in ways that determine its long-term thermal and mechanical character (e.g. Sandiford & McLaren 2002).
* demonstrating the  role of gravitational body forces in the evolution of the Earth's major mountain belts (Sandiford & Powell 1990; Sandiford 1988).
* demonstrating how tectonic stress is sourced at the global scale (Coblentz et al. 1993) in ways that explains the observed natural variability in stress state in our tectonic plates  (Coblentz et al. 1995; Coblentz & Sandiford 1995).
* demonstrating the links between intraplate earthquakes and geomorphic records  (Sandiford 2003) in ways that allows the development of geologically constrained models for earthquake hazard  (Quigley et al. 2007).
* demonstrating the geomorphic response to dynamic processes deep in the Earth's mantle and how it explains many previously enigmatic landscape features such  as Australia's unique record of continental tilting (Sandiford 2007), as well as emblematic landscapes such as the Lake Eyre Basin (Sandiford & Quigley 2008).
* linking earthquakes,  landslides   and  river incision in a new fundamental theoretical perspective (Egholm et al. 2013) that has application to understanding natural hazard vulnerability in settings such as the Indian Himalaya (Morrell et al., 2015) and Timor (Sandiford, 2008). 

 Professor Sandiford's has also worked on human energy systems helping to  quantify the impact of distributed energy technologies in mature energy markets (McConnell et al. 2013).

The impact of Professor Sandiford's research is evident his [citation metrics](#citation-metrics) (Google scholar  H-index = `r  my.profile$h_index`). He is a Fellow of the Australian Academy of Sciences. He has received several  honorific awards including the Australian Academy of Sciences Mawson Medal - a career award for "outstanding contributions to earth science in Australia".  He has an strong record of grant success including some $4.4 million in competitive research programs funding and $2.5 million in non-competitive funding since 2000 ^[this is in addition to the ~$23 million he has generated for his discipline, and ~$34 million for the University's interdisciplinary energy programs].   In 2016, the University of Melbourne awarded him the title Redmond Barry Distinguished Professor.

Beyond the academy, Professor Sandiford's work on the the thermal structure of the Australian continent contributed the key motivation for the search for geothermal energy in South Australia. His work on active tectonics and earthquake occurrence has been used in hazard assessment and has been used by Geoscience Australia to develop new approaches groundwater resource management. His work on tectonic stress has been used in unconventional resource development and assessment of storage potential for energy wastes. His work on the geomorphic evolution of the continent has seen application in biodiversity assessments. Finally, his work on trends in Australian energy consumption has impacted government policy settings.


## National geoscience leadership

In his role as Chair of the Science Advisory Board of AuScope ^[ Auscope administers the federal government's National Collaborative Research Infrastructure Strategy (NCRIS) program for the Earth Sciences], Professor Sandiford has played a key role in shaping the national geoscience research  agenda. In 2009, he conceived and led the successful $23 million Education Investment Fund (EIF) round 3 bid for the Australian Geophysical Observing System, which saw  $7.5 million invested at the University of Melbourne. In 2012, he was instrumental in putting together the University's $11 million component of the successful $51 million CCSNET EIF bid. Professor Sandiford was one of two geoscience representatives on the Environmentally Sustainable Australia working group as part of National Research Infrastructure Council (NRIC) framework that contributed to the “2011 strategic roadmap for the Australian research infrastructure - exposure draft”. In 2011, he led a group of geoscientists to produce the “Australian Earth Observatory - Infrastructure Roadmap” on behalf of AuScope. As the Australian representative on the Exploration Technologies Reference Group for the International Partnership for Geothermal Technologies, he contributed to the “IPGT Exploration Whitepaper” released in June 2011.  
 

## Promotion of interdisciplinary energy research

In his role as inaugural director of the Energy Institute (2010-2016) Professor Sandiford was responsible for coordination and  facilitation of energy research across the University of Melbourne. In this role he has  been responsible for building teams and seeding new interdisciplinary programs in areas as diverse as renewable energy integration, energy market design, direct geothermal utilization, geological carbon storage, and sedimentary basin management. The  programs he has have helped initiate have secured more than $34 million in external funding.

In his role as Director, Professor Sandiford's counsel has been sought by senior politicians and their advisors,  including  Victorian Minister for Energy Lily d'Ambrosio and SA State  Premier Jay Weatherill and Federal Minister for the Environment Greg Hunt, as well as industry participants such as AGL, Tas Hydro, PacHydro and the Clean Energy Council. 


## Science and development

Since 2002, Professor Sandiford has lead significant geological programs in developing regions across Asia, including in Timor-Leste, India, Bhutan, Indonesia   and Tibet, supported in part by Australian Government Department of Foreign Affairs and Trade aid prorgrams. He has initiated a Graduate Program in Asian Geoscience which has been instrumental in developing geoscience capability in host countries such as Timor Leste. Outcomes include the production of the first detailed geological maps of Timor Leste since its independence, as part of an ongoing program that aims to map the country at a scale of 1:50,000. In 2013, at the invitation of the Indian Government Department of Science and Technology, he particpated in a review the 2012 Kedarnath landslide disaster in which as many as 20,000 people may have perished (> 5000 confirmed). In 2011 he co-edited an international publication focused on the 2008 Wenchuan Earthquake in China, in which about 88,000 people perished and more than one million were displaced. He has worked closely with colleagues from IISc in Bangalore, India, to document the record of great Himalayan earthquakes in the central Himalaya using novel proxies in a program funded  jointly by the Australian and the Indian Governments. He is currently working with the Government of Bhutan to document the record of great earthquakes in the eastern sector of the Himalaya.

## Public engagement

Professor Sandiford has  contributed extensively to the national debate on environmental and energy policy issues, having contributed over 70 commentaries to major national newspapers (including op-eds in both the Fairfax - the Age and Sydney Morning Herald - and the Murdoch press - the Australian) and on-line venues (the Conversation, RenewEconomy, Business Spectator) . The broad reach of his  commentary is reflected in the statistics for his column on the Conversation website - Energy and the Earth - for which the readership stands at more than 930,000 individual reads.


#  1. Education and Employment History
* Chair of Geology, University of Melbourne 2010+
* Director, Melbourne Energy Institute, University of Melbourne 2009+
* ARC Professorial fellow, University of Melbourne 2000-2009
* Lecturer/Senior Lecturer/Reader, University of  Adelaide 1987-2000
* CSIRO postdoctoral fellow, University of Cambridge 1986-1987
* PhD, University of Melbourne 1985
* BSc(Hons), University of Melbourne 1978

#  2. Recognition
* Carey Medal, 2014 Geological Society of Australia 
* Hobbs Medal, 2012 Geological Society of Australia
* Mawson Medal, 2005  Australian Academy of Sciences
* Stillwell Medal(s), 2003, 2005 and 2009 Geological Society of Australia
* Elected Fellow, Australian Academy of Sciences, 2013 Australian Academy of Sciences
* Elected Fellow, Geological Society of Australia, 2011 Geological Society of Australia
* Distinguished Visiting Professor, Paris, France,  2008 Ecole Normale Supérieure
* ARC Professorial Fellow, 2005-2009 Australian Research Council
* ARC Professorial Fellow, 2000-2004 Australian Research Council
* CSIRO Postdoctoral Fellowship,  1986-1987 Cambridge University

# 3. Professional Service
* IMAGE project review, Pisa Italy, 2015 EU Commission
* Review of Geosciences,  2015  Victoria University, New Zealand, 
* Department Science and Technology, Indian Government Review of Kedarnath landslide disaster, Uttrakhand, India, May 2014. 
* EON Research Centre, Science Advisory Board, 2011-2012  RWTH Aachen Germany
* Strategic Roadmap for Australian Research Infrastructure, 2011 Department Industry, Australian Government
* SUNConnect Advisory Board, 2011
* International Partnership for Geothermal Technology, Exploration technologies working group, 2010-2012 
* Geology, Editorial Board, 1999-2001 and  2009-2011
* AuScope-AGOS EIF Science Advisor, 2009-2013
* ARC College of Experts, 2009-2011 Australian Research Council
* AuScope Science Advisory Board (Chair), 2007-2012 
* Australian Journal of Earth Science, Editorial Board, 2005-2008
* Tectonophysics, Co Editor-in-Chief, 2004-2009
* PMD*CRC Science Advisory Board, 2000-2002

# 4. Research funding (since 2000)
__Total funding __ $17,091,000 

* Competitive Research Program Grants (inc. ARC DP, ARC Linkage,AISRF, NDG)  $4,416,000
* Infrastructure grants at University of Melbourne (EIF, MNRF) $8,343,000
* Infrastructure grants at other universities (ARC LIEF) $1,875,000 
* Other non-competitive funding - $2,457,000

Current grants

* Indo-Australian plate Active tectonics program, CI Sandiford,  ARC Discovery,  $400,000 
* Geodynamic groundwater, CI Sandiford, Geoscience Australia, 2014-2016   $405,000 
* GipNet Siemic monitoring network, CI Sandiford & Gibson, EIF,  2015-2019, $1,200,000

# 5. Published work 

__Google Scholar__ 
`r  
#library(scholar)
#gs.id<-"qdYHZTgAAAAJ"
#my.profile <- get_profile(gs.id)
 paste("Total citations - ", my.profile$total_cites, ", ", "Hirsch-index - ", my.profile$h_index, ", ","i10-index - ", my.profile$i10_index) 
`

__Top five papers__

*	Egholm, D., Knusden, M.F., __Sandiford, M.__, 2013, Lifespan of mountain ranges scaled by feedbacks between landsliding and erosion by rivers, Nature, 498, 475–478, doi:10:1038/nature12218 
`r  gs("Lifespan of mountain ranges" )`
*	__Sandiford, M.__, 2007, The tilting continent: a new constraint on the dynamic topographic field from Australia, Earth and Planetary Science Letters, 261, 152-163  doi: 10.1016/j.epsl.2007.06.023 `r   gs("The tilting continent")` 
*	__Sandiford, M.__, McLaren, S., 2002, Tectonic feedback and the ordering of heat producing elements within the continental lithosphere, Earth and Planetary Science Letters, 2002, 204, 133-150
`r   gs("Tectonic feedback and the ordering of heat producing")` 
*	Coblentz, D., __Sandiford, M.__, Richardson, R, Zhou, S., Hillis, R., 1995, The origins of the Australian stress field, Earth and Planetary Science Letters, 133, 299-309. `r  gs( "The origins of the intraplate stress field in continental Australia")` 
*	__Sandiford, M.__, Powell, R., 1986, Deep crustal metamorphism during continental extension, ancient and modern examples. Earth and Planetary Science Letters, 79, 151-158. `r  gs("Deep crustal metamorphism during continental extension")`  

__Other Key papers (total of 170 peer-reviewed publications)__

*	Morell, K.D., __Sandiford, M.__, Rajendran, C.P., Rajendran, K., Fink, D., Alimanovic, A., Sanwal, J., 2015, Geomorphology reveals active decollement geometry in the central Himalayan seismic gap, Lithosphere, 7, 247-256, doi:10.1130/L407.1  `r   gs("geometry in the central")`
*	McConnell, D., Hearps, P., Eales, D., __Sandiford, M.__, Dunn, R., Wright, M., Bateman, L., 2013, Retrospective modeling of the merit-order effect on wholesale electricity prices from distributed photovoltaic generation in the Australian National Electricity Market, Energy Policy, 58,17-27, doi:10.1016/j.enpol.2013.01.052 `r  gs("Retrospective modeling of the")`
*	__Sandiford, M.__, 2008, Seismic moment release during slab rupture beneath the Banda Sea, Geophysical Journal International, 174, 659–671  doi: 10.1111/j.1365-246X.2008.03838.x 
`r  gs("slab rupture beneath the Banda Sea" )`
*	__Sandiford, M.__, 2003, Neotectonics of southeastern Australia: linking the Quaternary faulting record with seismicity and in situ stress, eds Hillis, R.R. Muller, D., Evolution and dynamics of the Australian Plate, Geological Society of Australia, Special Publication, 22, 101-113 `r  gs( "Neotectonics of southeastern Australia")` 
*	Coblentz, D., __Sandiford, M.__, 1994, Tectonic stresses in the African plate: Constraints on the ambient stress state, Geology, 22, 831-834. `r   gs( "Tectonic stresses in the African plate")` 
*	Coblentz, D., Richardson, R.M., __Sandiford, M.__, 1994, On the gravitational potential of the Earth's lithosphere, Tectonics, 13, 929-945. `r  gs( "gravitational potential")`
*	Turner, S., __Sandiford, M.__, Foden, J., 1992, Some geodynamic and compositional constraints on "post-orogenic" magmatism, Geology, 20, 931-934. `r    gs("Some geodynamic and compositional constraints")` 
*	__Sandiford, M.__, Powell, R., 1991, Some remarks on high temperature-low pressure metamorphism in convergent orogens, Journal of Metamorphic geology, 9, 333-340. `r   gs( "metamorphism in convergent orogens")` 
*	__Sandiford, M.__, 1989, Horizontal structures in granulite terrains : a record of mountain building or mountain collapse? Geology, 17, 449 - 452. `r   gs( "Horizontal structures in granulite terrains")` 

__Selected Invited and Keynote talks__

* EEC Eenergy Efficiency Council, National conference 2013, Melbourne, December 2013
* 3rd International Student Energy Summit, ISES 2013, Trondheim, Norway. June 2013.
* 24th IGC,  Brisbane  Global Geoscience Initiative, August 2012 
* IUGG, Melbourne, July, 2011
* NGRI Jubilee Celebrations, October, 2011, Hyderabad, India 
* International Himalayn geodynamics, Wadia Institute, November, 2011
* IISC Bangalore, india, April, 2010 
* GLADE,  California, July, 2010
* SOTA, Greece, September, 2010 
* Imperial College, London, June 2009, 
* Janet Watson Meeing, London May 30th 2009
* SERN, Dili, Timor 2009
* Geomorphology2009, Melbourne, July 2009
* Ecole Normale Superieur, Paris, June, 2008
* Grenoble, July 2008
* Gordon Conference, Italy, August 2008
* Thomson Conference, ETH, Zurich,  2007  



# 6. Supervision and mentoring

__PhD supervsion__ 

*	Dr Shoahua Zhou, 1990,  current position Senior Petroleum Engineering Consultant, Saudi Aramco
*	Dr Jo Arnold, 1993,  current position Consultant, Magill Conulting, Adelaide
*	Dr Ian Scrimgeour, 1993,   current position Director, Northern territory Geological Survey
*	Dr Jon Teasdale, 1997,  current position Global strategist, Shell, Amsterdam
*	Dr Bruce Schaefer, 1998,  current position Senior Lecturer, Macquarie University
*	Dr Eike Paul, 1999,   current position, Head of Geology RSE, Vienna
*	Dr Sandra McLaren, 2001,  current position Lecturer, University of Melbourne
*	Dr Narelle Neumann, 2002,  current position Principal Scientist, Geoscience Australia
*	Dr Victor Tokarev, 2003,  current position Senior Exploration Geologist, Santos, Adelaide
*	Dr Mark Quigley, 2007, current position Assoc. Professor, University of Melbourne
*	Dr Kim Ely, 2009,  current position Research fellow, Stonybrook University, USA
*	Dr Sara Jakica, 2011,   current position Multi-client business manager, HiSeis, Perth
* Dr Jaeryul Shin, 2012, lecturer, Kyungpook National University, Korea 
* Dr Ben Harrison, 2015, 
* Dr Steven Geroe, 2015, (PhD in Melbourne School of Law)
* Dr Dimitri Lafleur, 2017, current position, CSIRO
* Dr Dylan McConnell, 2020, current position, University of Melbourne
* Dr Tamarah King, 2020, current position, Cambridge University

__Postdoctoral  supervision__

* Prof Simon Turner,   current position Laureate Professor, Macquarie University 
* Dr David Coblentz,   current position Senior fellow, Geodynamics, LANL, New Mexico, USA 
* Prof Kurt Stuwe,   current position Professor, Graz University, Austria 
* Dr Geoff Fraser,   current position Geoscience Australia 
* Dr Peter Haines,    current position Geological Survey Western Australia 
* Prof Martin Hand,    current position Porfessor University of Adelaide 
* Dr Sandra Mclaren,    current position, Lecturer, University of Melbourne 
* Prof David Egholm,   current position Aarhus University, Denmark 
* Dr Simon Bodorkos,    current position Geoscience Australia
* Dr Steve Boger,   current position Senior Lecturer, University of Melbourne
* Dr Kristin Morell,  current position Assoc. Professor, University of Califonia, Santa Barbara, US.
* Dr Tim Rawling,  current position CEO, AuScope, Melbourne 
* Dr Guangwei Li, current position, Academic, Nanjing University
* Dr Januka Attanayake, current position Research Fellow, University of Melbourne

# 7. International development

__DFAT sponsored Masters students__

*  Phuntsho Pelgay, Bhutan, 2014-2015, Earthquake hazard in Bhutan
*  Yolgi Alawendra, Indondesia, 2012-2013, Geothermal potential of the Central Sumatra Basin

__Geological mapping in Timor Leste__

* 1:50,000 Geological map sheet Atauro, Timor Leste, 2005
* 1:50,000 Geological map sheet Dili, Timor Leste, 2012
* 1:50,000 Geological map sheet Manatuti, Timor Leste,  2013
* 1:250,000 Landslide distribution map, Timor-Leste (West), 2010

 
# 8. Public engagement


__Columns__  [Energy an the Earth](https://theconversation.com/columns/mike-sandiford-228) on [the Conversation](https://theconversation.com) (2012+). Total 53 Posts viewed  more than  703,000 times.

__National Press - Selected op-eds__

* Cherry-picking contrarian geologists tend to obscure scientific truth, December 31 2011,
[the Australian](http://www.theaustralian.com.au/national-affairs/opinion/cherry-picking-contrarian-geologists-tend-to-obscure-scientific-truth/story-e6frgd0x-1226233605954)
* The scale of the effect we have on the planet is yet to sink in, May 23rd  2011,
[the Age](http://www.theage.com.au/it-pro/the-scale-of-the-effect-we-have-on-the-planet-is-yet-to-sink-in-20110522-1eyqk)
*  Fossil fuels will run out of gas when the solar revolution arrives, March 22nd  2011,
[the Sydney Morning Herald](http://www.smh.com.au/business/fossil-fuels-will-run-out-of-gas-when-the-solar-revolution-arrives-20110321-1c3qe.html)
* Solar and wind power crucial for climate future, February 18th 2011, the Canberra Times
* Do renewable energy by the numbers, and it all adds up, June 24th 2010,
[the Age](http://www.theage.com.au/it-pro/do-renewable-energy-by-the-numbers-and-it-all-adds-up-20100623-yywm)
* Geology points to dangers ahead, May 6th 2009,
[the Australian](http://www.theaustralian.com.au/opinion/geology-points-to-dangers-ahead/story-e6frg6zo-1225710269931)


__National Press - Selected TV \& Radio interviews__

* Power system can't take the heat, [ABC radio National AM  with Michael Brisenden](http://www.abc.net.au/am/content/2013/s3926465.htm), 16th January 2014. 
* Fractured future, May 5th 2005 [ABC TV Catalyst ](http://www.abc.net.au/catalyst/stories/s1360803.htm)
* Australia moves north, ABC Radio National Late Night Live with Phillip Adams, 10th February 2004
* Australian Earthquakes,
ABC  Radio National Breakfast with Peter Thompson, 5th June 2003
* Earthquake Study
ABC Radio National Breakfast with Peter Thompson, 20th December 2002
* Geothermal power operating in South Australia, [ABC Science show](http://www.abc.net.au/radionational/programs/scienceshow/geothermal-power-operating-in-south-australia/4723534),  June 1 2013, 
* Researcher delves into Earth's crust, [ABC Radio National PM](http://www.abc.net.au/pm/content/2005/s1290603.htm), January 27, 2005
*Good and bad of fracking,  [ABC Radio, Country Hour](http://www.abc.net.au/news/2013-08-19/fracking-mining-gippsland-otway-sandiford/4896242),  19 Aug 2013

__Public lectures__

* [Intelligence Squared debates - Will coal-fired power soon be obsolete](http://www.wheelercentre.com/events/coal-fired-power-will-soon-be-obsolete), Melbourne, October 18th 2014,  Wheeler Centre
* Womad Earthstation, October 2011, Adelaide, October 
* Geological Society of Australia Public Lecturer, 2004
* Mawson lecture, Why oz quakes?, February 2004, Geological Society of Australia, Hobart Tasmania


__Independent commentary__

*  Finding majesty in the earth's dynamics, July 14  2014, [the Age](http://www.theage.com.au/national/education/voice/finding-majesty-in-the-earths-dynamics-20140708-3bkll.html)
* River deep, mountain high, July 8, 2013, [Sydney Morning Herald](http://www.smh.com.au/national/education/voice/river-deep-mountain-high-20130704-2pecq.html)
 * River deep, mountain high: New study reveals clues to lifecycle of world's iconic mountains, June 27 2013, [Science daily](http://www.sciencedaily.com/releases/2013/06/130627102631.htm)
*  Predicting the quake, April 18  2005,  [the Age ](http://www.theage.com.au/news/Education-News/Predicting-the-quake/2005/04/15/1113509921667.html?from=moreStories)
* Asian earthquake risk suggested before tsunami disaster, January 26 2005,
[New Scientist](https://www.newscientist.com/article/mg18524843-900-asian-earthquake-risk-suggested-before-tsunami-disaster/)
* Australia’s quake-ridden past is uncovered, June 7 2003,
[New Scientist](https://www.newscientist.com/article/mg17823982-300-australias-quake-ridden-past-is-uncovered/)
* Brown coal phase-out may be scrapped,  August 9 2012, [ABC Environment]( http://www.abc.net.au/environment/articles/2012/08/09/3564105.htm)
