---
title: "what on earth ..."
description: "reflections on a life of science, some contributions, some anecdotes.
  \n"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

reasons:- 
eternal husband [[Bridget Robinson](pdfs/personal/bid_celebration.pdf)], father, friend, sailor,  geologist 



investigations:-
[earth dynamics](pdfs/peer/2020_Tectonics.pdf), [earth energetics](pdfs/peer/2002_EPSL_b.pdf), [landscape evolution](pdfs/peer/2013_nature12218.pdf), [continental evolution](pdfs/peer/2010_JMG_a.pdf) and [energy systems](pdfs/peer/2015_AppEnergy.pdf)



privileges:- to have worked among communities that have lived for millennia in some of the most dynamic and remote parts of our planet including [Timor](https://msandifo.github.io/blog/_site/posts/2016-04-16-travelling-with-timor-leste/), [Tibet](https://theconversation.com/raising-tibet-58483),  [Xinjiang](https://msandifo.github.io/blog/_site/posts/2020-02-03-a-precarious-geological-bargain/) and [Bhutan](https://theconversation.com/the-will-of-government-is-key-to-energy-access-58332), and some places to remote for community (Enderby Land, Northern Victoria Land); to have known love and  so much more. 

[reflections](https://theconversation.com/columns/mike-sandiford-228):-  [earth](https://msandifo.github.io/blog/_site/posts/2020-02-04-cherrypickingcontrarian/) and [energy policy ](https://msandifo.github.io/blog/_site/posts/2020-02-04-renewableenergybythenumbers/) 

notifications: Redmond Barry Distinguished Professor Emeritus (University of Melbourne), 
<!-- former Chair of Geology in the School of Earth Sciences and founding Director of the [Melbourne Energy Institute](https://energy.unimelb.edu.au),  -->
fellow [Australian Academy of Science](https://www.science.org.au/profile/michael-sandiford)

### [recent commentary](pop.html)

- reflections on the purpose of Geology- [Motivations 1](https://geo-down-under.geoscience.education/the-last-vicmanian/),  [Motivations 2](https://geo-down-under.geoscience.education/children-of-the-revolution/), [Motivations 3](https://geo-down-under.geoscience.education/earth-system-services/)
- [fugitive emissions due to unconventional gas](https://msandifo.github.io/blog/_site/posts/2020-09-25-tropomi-and-gas-emsissions/)

- [on the "gas fired recovery"](https://msandifo.github.io/blog/_site/posts/2020-09-05-gas-fired-recovery/)


 

### [recent publications](pubs.html)
- [geomorph](pdfs/peer/2022_EPSL.pdf) - elasticity, gravity and the Finke Gorge
- [geochem](pdfs/peer/2021_GGG.pdf) - anomalous arc magmas
- [volcanism](pdfs/peer/2021_ESR.pdf) - Holocene intraplate volcanism in East Asia
- [environment](pdfs/peer/2021_Elementa.pdf) - on Mercury pollution from electricity generation in the Latrobe Valley 
- [geodynamics](pdfs/peer/2020_Tectonics.pdf) - on stress distribution and dynamics of subducting slabs 
- [earthquakes](pdfs/peer/2020_BSSA.pdf) - on Australia's largest earthquake in almost 30 years
- [groundwater](pdfs/peer/2020_Hydrogeol.pdf) - some novel insights into the iconic Great Artesian Basin
- [techniques](pdfs/peer/2020_GTE.pdf) - on the measuring thermal diffusivity in soils  
- [economics](pdfs/peer/2020_CSR.pdf) - on the impact of market power in the Australian energy system




<!-- ### Tampa^[written while working in the Pilbara at the time of the Tampa crisis. It was an event that had a profound impact on me - a "geological fault line" of shame on the Australian psyche that demonstrated our diminished humanity. We continue to live in the shadow of this awful event, for which we owe the world an apology.] -->

<!-- Who are we who\ -->
<!-- will not say sorry\ -->
<!-- so afraid for what?  -->


<!-- Of what we have or\ -->
<!-- those that have\ -->
<!-- what we have not? -->


<!-- So should we not\ -->
<!-- say our sorry\ -->
<!-- and be not afraid?  -->

<!-- Of being. -->
