---
title: "Travelling with Timor Leste"
description:  On the ghosts of _Jakarta dua_ and the shocking realisation hidden in the dark shadows of Timor landscapes.
date: 04-16-2016
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

 

It took several trips before I began to understand the scale of the horror.  It  was 2009 and I was working in the Ainaro district in Timor Leste, not far from  Ramelau - Timor’s highest peak.

A rural centre,  Ainaro is built on a massive conglomerate “fan”, the origins of  which can be traced into a huge head-wall scarp in the Ramelau range. I was convinced the conglomerate was the result of a truly massive landslide - one that just might have  “taken out” a peak even higher than Ramelau. Along with one of my students from Melbourne and a young Timorese geologist, Johnny, we were mapping the geology of the landslide deposit. 

We knew the deposit couldn’t be very old, in geological terms, since the island of Timor only emerged from the sea  just a few million years ago. Understanding when and why the landslide formed would help us better understand the  risk elsewhere in Timor. That my student was of Timorese extraction, with family connections to Ainaro, made the fieldwork all the more special.

We were driving several kilometres south from Ainaro, to an outcrop I had briefly visited on a previous trip. The outcrop comprised a spectacular ~40 m cliff cut down through the conglomerate, the clifftop only a few metres away from the road. I had hoped the cliff exposures held the clues to the age of this extraordinary deposit.

As I explained our destination en route, Johnny responded “we must be going to Jakarta dua”  (literally “Jakarta two”).

Nonplussed, I asked naively  “why Jakarta dua?”

Without hint of recrimination, Johnny responded  “when you go to Jakarta you don’t come back.”

And with that, my imagination cut loose flashing terrifying images of just what might have been perpetrated at that cliff  under Indonesian occupation? To help deal with my growing sense of unease, I  changed our itinerary and set about finding other outcrops to do our work.

And as we did so I began to see the landscape in an entirely new light.  Now as I scanned the mountain slopes, the faint remnants of paddy terraces, now  largely washed away,  shouted “why did you not notice us before”. 

The landscape was now everywhere imbued with a dark shadow as testimony to the  brutal rural depopulation that had occurred under the Indonesian occupation in the late 1970’s and early 1980’s.  Some reports suggest that then as many as [one hundred and eighty thousand Timorese perished](http://gsp.yale.edu/sites/default/files/files/UN%20verdict%20on%20East%20Timor.pdf) in the ensuing starvation. The abandoned fields are just one testimony to the magnitude of a genocide, [as described by Australian expatriate Ben Kiernan](http://gsp.yale.edu/sites/default/files/03-263_ch_09.pdf), that took the lives of one fifth of the population. Kiernan reports that visitors to Ainaro in late 1975 found the town entirely deserted of Timorese.
  
  And so I ask myself “why did it take me so long to recognise this tragic human imprint on the landscape?”  
  
  It is no comfort to recognise I am not alone. Gough Whitlam toured Timor in 1982 as the genocide played out. In an [ABC interview in 1999, Whitlam](http://www.abc.net.au/worldtoday/stories/s71200.htm)  is quoted “What I said in ‘75, what I said in '82 was completely correct. I went all round East Timor in '82 and there was no risk at all.” With [ample commentary concerning Whitlam’s dismal record on East Timor](https://newmatilda.com/2014/11/17/whitlam-timor-and-great-men-history-myth/), it need not be repeated here.
    
The point is that the answer to my question is quite simple. We most often see only what we look for, and for most of us there is nothing quite so blinding as self interest.  Mine was my sharp focus on geology, so sharp it occluded a tragic human story. Whitlam’s, I can only presume, was on justifying his record.
  
 Perhaps I am again showing my naivety, but I confess  it is a growing sense of unease, even shame,  that motivates me to write this piece.
    
My unease is despite a pride in our national aid effort, and especially of our actions in times of dire need - such as followed the Banda-Aceh earthquake and in Timor once the the horror inflicted by the militias became apparent, in the aftermath of the vote for independence in 1999. I count my work in Timor as just one small contribution to that effort^[My Timorese work is part of an ongoing collaboration with the Timor Leste geological agencies to map the geology of Timor and document its natural hazards</a> designed to provide basic understanding of Timor’s geological heritage. By forming teams involving Timorese geologists working with Australian postgraduate students, supervised by my colleagues, we also help provide technical skill development.  But the learnings are very much two-way and I have always thought the greatest leanings are the life lessons passed to my students from their Timorese colleagues such as Johnny.  After spending a few months in rural Timor, I am convinced my students arrive back in Melbourne,  with a much expanded sense of themselves, a better understanding of the special privileges they have been afforded as Australians, and a commitment to being better citizens of the world. While not linked formally, the ambitions of my program are very much aligned with those of the [Australian Government’s New Colombo Plan](http://dfat.gov.au/people-to-people/new-colombo-plan/pages/new-colombo-plan.aspx), the principles of which I strongly endorse.].
    
No, my unease is due to the way my government continues to game the Timorese over the [position of its maritime boundary](http://www.abc.net.au/news/2016-04-11/east-timor-to-negotiate-maritime-border-with-australia-at-un/7316674). That we refuse to engage with formal international protocols that define where that boundary should be, is something that I find unconscionable. That our government stands <a href="http://www.smh.com.au/federal-politics/political-news/australia-ordered-to-cease-spying-on-east-timor-by-international-court-of-justice-20140303-hvfya">accused of bugging Timorese government offices to advantage its unconscionable position</a> is an outrage that I think should shame every Australian. Does it surprise that the minister responsible, [Alexander Downer  subsequently consulted for Woodside petroleum](http://www.theaustralian.com.au/national-affairs/foreign-affairs/how-canberra-and-woodside-bugged-timor-pm-to-strip-fledgling-nation-of-oil-billions/story-fn59nm2j-1226795417836), a company that had more than a little interest in the position of the boundary?
      
The Australian government has made many excuses to justify its position on the maritime boundary. One claims our territorial waters should be extended to a putative edge of the continental shelf which it places close the Timor Trough, well beyond the median line. 
      
The Timor trough is something of a geological enigma. There is debate as  to whether it constitutes a tectonic plate boundary.   Maybe it did, for a short time several million years ago, but today the trough is seismically inactive - a sure sign it is now no  plate boundary. Today Australia once again effectively travels with Timor as part of the Indo-Australian plate.  
      
Critically, Timor is largely made of the very same rocks that lie beneath the sea floor on Australia’s own north-west shelf. Most interpretations have Timor as part of the continental shelf, albeit broken up and interleaved with bits of the Indonesian volcanic island chain in great thrust stacks that pushed the  island from the sea a few  million years ago. Technical detail I know, but if it is made from the same shelf, there can be no continental “shelf edge” between Timor and Australia^[My geological “hunch” is that the former Australian continental shelf edge lies buried beneath Timor in the great thrust stack that was created as the island emerged from the sea several million years ago. In this scenario, the Timor Trough is underpinned by Australian continental shelf, and the deep bathymetry that defines it represents the flexural bending of the Australian shelf in response to loading by the Timor thrust stack.]   
      
So the  geological case for varying the boundary from the international norm defined by the Rules of the Sea is weak at best. But so what if it were, the moral case is bereft. The only reason that we would dispute the position of the boundary is economic. Its position defines the access rights to the rich geological resources beneath the Timor Sea. 
      
  So let’s not beat about the bush. Let’s just call the Australian position for what it is - an “oily-greed”.
      
But in our oily-greed don’t we show ourselves for hypocrites when criticising the Chinese for their active geological appropriation of the South China Sea? 
      
And in our appropriation of the Timor Sea, don’t we reveal a greed at odds with our record of generosity in times of need.  
      
 And for the opportunity of a few mere petro-dollars, don’t we deplete a more valuable,  intangible resource - the respect of our neighbours.
      
The [government of Timor Leste has again called](http://www.smh.com.au/federal-politics/political-news/east-timor-takes-australia-to-un-over-sea-border-20160411-go39tl.htm) on the  United Nations to resolve the maritime boundary dispute. 
The initial Australian government response indicates little hope we are prepared to begin the process of removing the self inflicted stains of our “oily-greed”.  
        
 Meanwhile, the ghosts of “Jakarta dua” shout at me “surely you can be better, surely it’s time for you to travel with Timor Leste”.
        
## Postscript
        
For those interested in the grim details of  “Jakarta dua”, an account of Max Stahl’s visit to the site in 1999  has been [posted](https://lists.riseup.net/www/arc/east-timor/2016-04/msg00096.html">https://lists.riseup.net/www/arc/east-timor/2016-04/msg00096.htm). It makes confronting reading and confirms my worst fears. [Max Stahl](https://en.wikipedia.org/wiki/Christopher_Wenner)  has played a pivotal role in documenting the atrocities committed in Timor Leste, including the filming of the [Santa Cruz massacre](ttps://en.wikipedia.org/wiki/Santa_Cruz_massacre) in 1991.  
        
## Notes
        

 This article is republished from [The Conversation](http://theconversation.com) under a Creative Commons license. Read the [original article](https://theconversation.com/travelling-with-timor-leste-57635).
        