---
title: "Geology points to dangers ahead"
description: |
  A differnce of opinion with a predecessor - Op-ed originally published in the Australian, May 6th 2009
date: 05-06-2009
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
IN his recent contributions to the climate change debate, Ian Plimer tells us the geological record should allay any concern that rising carbon dioxide concentrations in our atmosphere will disrupt the climate.

CO2 is a trace gas that has never affected climate, he says. But there are other readings of the geological record that lead to a profoundly different conclusion. Geology tells us that for at least the past 200 million years there has never been so much CO2 in the air with so much ice on the land; that rising CO2 always accompanies a melting of the ice and that when the ice melts, seas rise fast.

Geology tells that at present CO2 levels the climate rules are changed.

We are not the first people to face the prospect of a rapid rise in the sea level. At the height of the ice age about 18,000 years ago, the sea was 130m lower than today. By 10,000 years ago the seas had risen to their present heights, reducing the continental landmass by a staggering 8 per cent. For much of this time Tasmania was connected to the mainland and people lived in what is now Bass Strait. The people living there - the Vicmanians - were confronted with the terrible reality that their land was drowning. When the last land bridge broke about 13,000 years ago, seas were rising at more - possibly much more - than 2m a century.

That the land of the Vicmanians and their fellow peoples is now largely submerged explains why we have such a fragmentary record of the first Australians: for the first 30,000 years of human occupation of this continent, most people lived along former coastal fringes now long since submerged.

Changes in sea level also go hand in hand with the amount of CO2 in the atmosphere. Between 18,000 and 10,000 years ago, the concentration of CO2 rose from about 200parts per million to 280ppm at about 1ppm a century. CO2 is now rising at 2ppm a year, more than 200 times faster than when Vicmania drowned. CO2 levels are now at 380ppm, way outside the natural realm of our present ice-age epoch. Alarmingly, the rate of increase is doubling every 30 years, with present trajectories heading towards CO2 levels this century that our planet has not seen for 30million years.

We now understand that the ice age cycle is driven by subtle wobbles in our planetary orbit around the sun. If CO2 levels remained within their ice-age limits, then we would expect the wobbling to drive us back into another ice age, slowly cooling the planet during the next 50,000 years or so.

However, there is a deeper and more disturbing lesson in the geological record.
The last time there was so much CO2 in the atmosphere was during the Pliocene epoch about five million years ago. The rhythms of that Pliocene world were fundamentally different and less extreme than those of the ice-age world of the past few million years. The Pliocene world was warmer, less windy and less variable than today: a world where El Nino was the norm and seas were so much higher that they extended inland across western Victoria into southern NSW, flooding most of the Murray Basin. It was a world where not even our orbital wobbles could drive us into and out of ice ages. Geology warns that rising CO2 levels are committing to a world of higher sea levels: a world more like the Pliocene than today, with a different set of climate rules.

The cause of our problem is simple. We have taken for granted a fundamental service provided by our climate. We have built our cities along the sea front, not understanding that the sea level is set by the climate. Now we know that sea levels have changed in the past and will in the future. Rising CO2 is compromising our climate's ability to balance the proportions of ice and water required to maintain present sea levels.

Many are alarmed by what might happen to our climate; some are sceptical that anything will; even fewer appreciate the inevitability that it will change, as so clearly written in the geological record. In the same way as Plimer, I understand there is nothing new in such change. I, too, worry that alarmist claims that the planet is imperilled speak to a woeful ignorance of the geological record and confuse the crisis we face. It is future generations, not the planet, that should be the focus of our concern. We have no useful moral tools for understanding how to frame issues of intergenerational equity raised by climate disruption. Confounding the geological record may not much matter for the planet - it has seen it all before - but could affect future generations, who will have to bear any burdens of rising seas and changing climates.

Geology tells us clearly that not for several hundred million years have we had so much CO2 in the atmosphere with so much ice on the land. Independently of any model predictions of the climate scientists, the geological record serves a warning. In raising CO2 levels we are committing to a world different from that on which civilisation has developed, to a world where the rules of our present ice-age epoch will no longer apply, a world of higher seas.

Unlike Plimer, my reading of the geological record tells me we should be cautious how we modify our atmosphere lest we condemn many future peoples to the fate of the last Vicmanians.