---
title: "A Precarious Geological Bargain"
description: |
  The ancient Silk Roads skirting  the great mountains and deserts of central Asia, weave a magic thread through a region that has played a special role in history.
date: 04-18-2016
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



The landscapes of the Xinjiang province of western China are very special.

It is here the ancient trade routes of the [Silk Roads](https://en.wikipedia.org/wiki/Silk_Road) skirt  the great mountains and deserts of central Asia, weaving a magic thread through a region that has played a special role in history.

Xinjiang is the home to the Uyghur, a place where the cycles of life and geology meet in ways that are both mystical and enthralling. 

In southern Xinjiang,  Uyghur villages huddle between the Western Kunlun Range, to the south, and the foreboding [Taklamakan Desert](https://en.wikipedia.org/wiki/Taklamakan_Desert) further north - the name of which loosely translates to  "go in and you will never come out".

In the region around Sanju, in the Hetian prefecture, the villages are inset into narrow valleys literally carved into the edge of the desert at the foot of the mountains.  Separated by stretches of barren desert, these valleys are the only places where water and soil combine in sufficient quantities to sustain communal life. The contrast between the serene, verdant valleys and the barren desert beyond is truly surreal.


<image id="118982" align="centre" caption="The Uyghur village of Sanju, southern Xinjiang, viewed from the desert above." zoomable="true" />


Glaciers high up in the Kunlun feed the valleys with water enough to sustain irrigation for only a few kilometres from the mountain front. Once free flowing water is exhausted,  the valleys  disappear beneath advancing desert sands -  the boundary between like a conflict zone in the epic battle between the wit of man and the forces of nature. 

<image id="118996" align="centre" caption="The limits of communal life depend on the amount of water available for irrigation. The photo shows the desert dunes at the downstream limit of irrigation in one of the valleys incised into the rising Sanju Anticline, the axis of which traces the distant hills." zoomable="true" />

The melt water carries with it a precious “rock flour” ground from bedrock by  mountain glaciers far above.  This vital silt helps replenish the soils in the valley floors, but also feeds the voracious desert beyond with a ready supply of ammunition to advance its cause. 

 
## A precarious bargain

The valleys that provide succour for the Uyghur are, in every sense, active geological phenomena. The valleys carve their way through older river sediment pushed upwards by forces that drive the  mountain front  relentlessly onto the desert.    


The valleys are most densely populated where the crust is actively "buckling" in response to these forces, with great folds in the landscape  emerging out from the desert [1]. The reason is simple, the buckling constricts the valleys and so focuses the water enough to sustain year round irrigation. 

<image id="118981" align="centre" caption="The Sanju Anticline exposed in the walls of the Sanju valley. The folded strata comprise old river deposits crumpled above the tip of a blind fault buried several kilometres below." zoomable="true" />


But the catch is that the folds sit above the tip of a [blind thrust fault](https://en.wikipedia.org/wiki/Thrust_fault#Fault-propagation_folds) that bites northwards from the mountain front several kilometers beneath the surface. With each fault rupture, the overlying anticlinal fold is squeezed just a little bit tighter, forcing the land surface to buckle upwards in small increments as its seismic waves propagate their deadly message.

With the Uyghur communities congregating in the valley segments carved into the most rapidly rising parts of the landscape there is a very real sense that life here is predicated on a precarious bargain with geology [2]. 

<image id="118986" align="centre" caption="Shaded topographic image of the region of the Uyghur settlements in southern Xinjiang, along the western Kunlun Range front. As north flowing rivers exit the range front headed towards the Taklamakan desert, they debouch gravels in _distributary fans_. As they encounter the  Sanju Anticline, the streams gather together again, in gently incised valleys. It is here the Uyghur have built their villages, and  where the ancient Silk Road traced a magic thread connecting civilisations. The blue and white symbols represent large earthquakes from a global catalogue of events of magnitude greater than 5.5 since 1975." zoomable="true"/>


 


## Cycles in cycles

When the desert wind blows from the north in winter, it blows with a fierce cold, thick with dust, across the Uyghur villages, returning the "rock flour"  to the mountains from which it came. With their beautiful tall hedgerows, the deepest carved valley segments afford the most protection from the biting, choking wind.

As the dust eventually settles on the mountain front as loess, it produces an ethereal landscape draped in a strangely comforting blanket. The image is of  a cremated land seemingly suspended in time, completing the cycle of dust from mountain to desert and back again. 

<image id="118978" align="centre" source="Photo by Mike Sandiford" caption="Loess draped foothills of the Western Kunlun, along the edge of the Taklamakan desert, near the village of Sanju." zoomable="true" />

It seems to me, this cycle is poignantly mirrored in the life of the Uyghur. To bury their dead, they climb the 50 metres or so up the near vertical valley walls to the desert above.  There, they dig shallow graves just a few metres from the cliff tops, knowing the graves will be gently mantled beneath a soft loess blanket when the winter winds blow the dust back from the desert beyond.

<image id="118993" align="centre" caption="A cemetary atop a valley wall. " zoomable="true" />

But they must also understand that as the rivers erode further into the buckling landscape,  those ancestral remains will eventually wash back down into the valleys below to enrich the precious soils, returning to the irrigated fields of their youth to nuture their descendants. 

In most parts of the world, the vastly different timescales of geological processes and human life make it hard to appreciate the resonances that connect us to the land to which we belong. But here, in the land between the Kunlun and the Taklmakan, these resonances are profound. For me they are amplified in great waves that enrich my spirit.

And for me it is deeply spiritual. 

Here it is especially easy to appreciate how people are connected to the landscape and how that connection links the lives that came before, and the lives that will come after, with the great forces that shape our planet. 

Here, there is a profound sense we are all part of a very much more important cycle, connecting our remarkable planet and all the people who inhabit it - in  life and in  death.

## A sense of place

For me,  the region of the Silk Roads in Xinjiang is special - a place where geology and life appear to merge seamlessly together.

But what I see in the Uyghur landscape is, I am sure, just a reflection of a universal truth - it is the sense of place that connects us to who we really are. 

And in that sense what is true of the Uyghur and their land is true of all people and all places.

----

## Footnotes

[1] My work was aimed at documenting just how fast these folds are forming and in so doing how rapidly the underlying fault are slipping. Sadly, like so many parts of the world, travel in southern Xinjiang has become increasingly difficult because of rising tensions between the ethnic population and the regional administration. The fieldwork referred to here took place in 2005 and 2009.
 
 
[2] The type of bargain predicated here is not uncommon across central Asia and the Middle East, where the conjunction of water and soil is often associated with active faults that periodically rupture in devastating earthquakes. 
This relationship has been explored in an extraordinary and wonderful scientific paper, one of my personal favourites,  by James Jackson, titled  ["Fatal attraction: living with earthquakes, the growth of villages into megacities, and earthquake vulnerability in the modern world"](http://rsta.royalsocietypublishing.org/content/364/1845/1911) - a must read for any budding geologist.  